language: python
cache: pip
env:
  global:
    # Doctr deploy key for chartbeat-labs/textacy
    - secure: "acT68V00S7dbJrRxsDnJooDo8LrKNhRQxpBfD3nnk3245IbvFbCPkpjWhnDJDEDk/wRpxizKJwPijseFZwXepb1ovJXirG7YHpFvlVNTcyR0uFSRUgI4Vy2oTJf1N5Ywbc/xd7lD1pAwcE23Lgaz7A369XUa+imYqJgA6POqAmJaeVzYcw5oiRu/QSl3y68ChAtwyP1LAjbJUyYO2i1R+TR/GKJPy4v6EmaUKll/2eGrOhQBBhjlpEnA3BLKUriPUComke67dIkGhYwyeyIn4Pe8hmK93L6Quhnce91y97ufovbAwFU8yG29gZpxhOuaGFArHPubB9crds9DnGsNXv9BpcCQ6H/ZP0vBw/8BT2d1J1gS9/+NJpur4qOs+PPCVNzvboOXw/4OL/DLf7w0u6hVu2BFLE3Mk2oNZgMm8hMR18j7bgf9XIifqjPe5bycIocYUMvDNYtvWb87oJ3FKGaJ7Mj/U5OqAUGlbGesA58ucmyi7bNsHrTwFKTYTeze+fk4Sn4oVZtOH/90Dtk1/L+bZ5yUYwBFlzdaGJpRKTnGM49wSaJ8sNg/TV6ZIU6L+gC+3H/tLR/oaROmkPmRns+PT3LbWB82W0RCRFT3Gjii8F1MxehGk5ieV+e6KRkXXh+9in3y9ozZhBbCynLKYPrCHH4tDJhfaBORlhOZ2lo="
matrix:
  include:
    - os: linux
      dist: trusty
      python: 2.7
    - os: linux
      dist: trusty
      python: 3.6
      env: BUILD_DOCS=true

# command to install dependencies and data
install:
    - "pip install -r requirements-dev.txt"
    - if [[ $BUILD_DOCS = true ]]; then
        python setup.py install;
        pip install doctr;
      fi
    - "python -m spacy download en_core_web_sm"
    - "python -m spacy link en_core_web_sm en"
    - "python -m spacy download es_core_news_sm"
    - "python -m spacy link es_core_news_sm es"
    - "python -m textacy download capitol_words"
    - "python -m spacy validate"

script:
  - set -e
  - if [[ $BUILD_DOCS = true ]]; then
      cd docs;
      make clean html;
      cd ..;
      doctr deploy . --built-docs docs/build/html/;
    fi
  - "python -m pytest -vv"
