language: python
os: linux
cache: pip
matrix:
  fast_finish: true
  include:
    - python: 3.6
      dist: bionic
      env: BUILD_DOCS=false
    - python: 3.7
      dist: bionic
      env: BUILD_DOCS=false
    - python: 3.8
      dist: bionic
      env: BUILD_DOCS=true

# command to install dependencies and data
install:
    - "pip install ."
    - "pip install .[dev]"
    - if [[ $BUILD_DOCS = true ]]; then
        pip install .;
      fi
    - "python -m spacy download en_core_web_sm"
    - "python -m spacy link en_core_web_sm en"
    - "python -m spacy download es_core_news_sm"
    - "python -m spacy link es_core_news_sm es"
    - "python -m spacy validate"
    - "python -m textacy download capitol_words"
    - "python -m textacy download lang_identifier"

script:
  - set -e
  - make test
  - if [[ $BUILD_DOCS = true ]]; then
      cd docs;
      make clean html;
      cd ..;
    fi
