name: build and test

on:
  push:
    branches: [ $default-branch, main, develop ]
  pull_request:  # run on all pull requests
  schedule:  # run weekly
    - cron: "0 12 * * 0"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
        os: [macos-latest, ubuntu-latest]  # windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: get pip cache dir
      id: pip-cache
      run: |
        echo "::set-output name=dir::$(pip cache dir)"
    - name: set up pip cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ matrix.os }}-pip-${{ hashFiles('setup.cfg') }}
        restore-keys: |
          ${{ matrix.os }}-pip-
    - name: install package and dependencies
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install -e .[build_and_test]
    - name: download language data
      run: |
        python -m spacy download en_core_web_sm
        python -m spacy download es_core_news_sm
        python -m spacy validate
        python -m textacy download capitol_words
        python -m textacy download lang_identifier --version 2.0
    - name: test with pytest
      run: |
        make test
